#!/usr/bin/env python3

import sys
import xml.etree.ElementTree as ET
import json
from pathlib import Path
import shutil

def main():
    if len(sys.argv) != 4:
        print("Usage: mirror <input_dir> <output_dir> <mirror_list>")
        sys.exit(1)

    input_dir = Path(sys.argv[1])
    output_dir = Path(sys.argv[2])
    
    cursors_to_mirror = set()
    with open(sys.argv[3], "r") as mirror_list:
        for line in mirror_list:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            cursors_to_mirror.add(line)

    ET.register_namespace("", "http://www.w3.org/2000/svg")

    for input_cursor in input_dir.iterdir():
        if not input_cursor.is_dir():
            continue

        if input_cursor.is_symlink():
            print(f"Symlink {input_cursor.name}")
            (output_dir / input_cursor.name).symlink_to(input_cursor.resolve().name)
            continue

        if input_cursor.name not in cursors_to_mirror:
            print(f"Skipping {input_cursor.name} (not in mirror list)")
            shutil.copytree(input_cursor, output_dir / input_cursor.name)
            continue

        print(f"Mirroring {input_cursor.name}")
        (output_dir / input_cursor.name).mkdir()
        with open(input_cursor / "metadata.json", "r") as f:
            metadata = json.load(f)
            for frame in metadata:
                filename = frame["filename"]

                print(f"  SVG file {filename}")
                
                tree = ET.parse(input_cursor / filename)
                svg_element = tree.getroot()
                width = int(svg_element.attrib["width"])
                
                graphical_elements = []
                for element in svg_element:
                    if element.tag.endswith("filter"):
                        continue
                    graphical_elements.append(element)
                
                svg_element.append(ET.Element("g", {"transform": f"translate({width}, 0), scale(-1, 1)"}))
                for element in graphical_elements:
                    svg_element.remove(element)
                    svg_element[-1].append(element)
                tree.write(output_dir / input_cursor.name / filename)
                frame["hotspot_x"] = width - frame["hotspot_x"]
        with open(output_dir / input_cursor.name / "metadata.json", "w") as f:
            json.dump(metadata, f)

if __name__ == "__main__":
    main()
